import numpy as np
from typing import Any

# kRPC.conf
KRPC_DEFAULT_ADDRESS: str
KRPC_CLIENT_NAME: str

# aegis.conf
TARGET_HZ: float
USE_SAS: bool
SAS_PROGRADE_ASCENT: bool
TARGET_LAT: float
TARGET_LON: float
PAD_POSITION_ECEF: np.ndarray[Any, Any]
LANDING_PAD_POSITION: np.ndarray[Any, Any]
ACTIVATION_ACTION_GROUP: int
ALT_HYPERSONIC: float
ALT_POWERED_DESCENT: float
ALT_HOVER: float
ALT_TERMINAL: float
ALT_LANDING: float
MAX_MISSION_TIME: float
LANDED_VEL_THRESHOLD: float
LANDED_ALT_THRESHOLD: float
FDI_THRESHOLD: float
RANDOM_SEED: int
NOISELESS_MODE: bool
GUIDANCE_KP_POS_LATERAL: float
GUIDANCE_KP_POS_VERTICAL: float
GUIDANCE_KD_VEL_LATERAL: float
GUIDANCE_KD_VEL_VERTICAL: float
GUIDANCE_KP_ATT: list[float]
GUIDANCE_KD_ATT: list[float]
GUIDANCE_ATT_NATURAL_FREQ: list[float]
GUIDANCE_ATT_DAMPING_RATIO: list[float]
ACCEL_CLAMP_FACTOR: float
PROCESS_NOISE_THRUST_COEF: float
GRAVITY: list[float]
GUIDANCE_MAX_TORQUE: list[float]
DEBUG_LOGGING: bool
LOG_TO_FILE: bool
LOG_FILE_PATH: str
HUD_ENABLED: bool
HUD_REFRESH_HZ: float
ROLL_CORRECTION_KP: float

# sensors.conf
SIGMA_ALT: float
SIGMA_ACCEL: float
SIGMA_VEL: float
SIGMA_GYRO: float
GYRO_BIAS_INSTABILITY: float
ACCEL_BIAS_INSTABILITY: float
MAHONY_KP: float
MAHONY_KI: float
GYRO_BIAS_UPDATE_GAIN: float
ACCEL_BIAS_UPDATE_GAIN: float
SENSOR_WARMUP_TICKS: int
SENSOR_WARMUP_GYRO_BIAS_SIGMA: float
SENSOR_WARMUP_ACCEL_BIAS_SIGMA: float

# ekf.conf
EKF_INITIAL_ATT_UNCERTAINTY: float
EKF_INITIAL_GYRO_BIAS_UNCERTAINTY: float
EKF_INITIAL_ACCEL_BIAS_UNCERTAINTY: float
EKF_INNOVATION_FAULT_THRESHOLD: float
ESTIMATOR_WARMUP_TICKS: int

# glideslope.conf
GLIDESLOPE_K_ALT: float
GLIDESLOPE_RATE_POWERED_DESCENT: float
GLIDESLOPE_RATE_HOVER: float
GLIDESLOPE_RATE_TERMINAL: float
GLIDESLOPE_RATE_LANDING: float
PD_KP_POS_LATERAL: float
PD_KD_VEL_LATERAL: float
HOVER_KP_POS_LATERAL: float
HOVER_KD_VEL_LATERAL: float
TERMINAL_KP_POS_LATERAL: float
TERMINAL_KD_VEL_LATERAL: float
LANDING_KP_POS_LATERAL: float
LANDING_KD_VEL_LATERAL: float
TARGET_BLEND_TICKS: int
PAD_OFFSET_EARLY_THRESHOLD: float
PAD_OFFSET_EARLY_ALPHA: float
GLIDESLOPE_TARGET_RATIO: float
HOVER_APPROACH_K: float
HOVER_APPROACH_MAX: float
TERMINAL_APPROACH_K: float
TERMINAL_APPROACH_MAX: float
ATTITUDE_KP: float
ATTITUDE_KD: float
ATTITUDE_MAX_PITCH_DEG: float

# engines.conf
PART_THRUST_AXIS: dict[str, tuple[float, float, float]]
DEFAULT_THRUST_AXIS: tuple[float, float, float]
