#!/usr/bin/env bash

# Delete all logs generated by AEGIS and recreate the logs directory.
# This script removes the entire 'logs' directory to ensure a clean state.
# It is safe to run multiple times; the directory will be recreated if missing.

set -euo pipefail

# Determine the project root (directory containing this script's parent)
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.. && pwd)"

LOG_DIR="$PROJECT_ROOT/logs"

# Remove the logs directory if it exists
if [[ -d "$LOG_DIR" ]]; then
  echo "Removing existing logs at $LOG_DIR"
  rm -rf "$LOG_DIR"
fi

# Recreate the logs directory
mkdir -p "$LOG_DIR"

echo "Logs directory reset at $LOG_DIR"
