from enum import Enum

class MissionState(str, Enum):
    STANDBY = "STANDBY"
    ASCENT_COAST = "ASCENT_COAST"
    DEORBIT_BURN = "DEORBIT_BURN"
    HYPERSONIC_COAST = "HYPERSONIC_COAST"
    POWERED_DESCENT = "POWERED_DESCENT"
    HOVER_TARGETING = "HOVER_TARGETING"
    TERMINAL_DESCENT = "TERMINAL_DESCENT"
    LANDED = "LANDED"
    HARD_ABORT = "HARD_ABORT"
